DO $$ 
BEGIN
    EXECUTE 'DROP TRIGGER IF EXISTS PrefixColourTrigger ON Organism';
    EXECUTE 'DROP FUNCTION IF EXISTS GetAverageLifespan()';
    EXECUTE 'DROP FUNCTION IF EXISTS InsertOrganism()';
    EXECUTE 'DROP SEQUENCE IF EXISTS org_pk';
    EXECUTE 'DROP TABLE IF EXISTS Animal';
    EXECUTE 'DROP TABLE IF EXISTS Plant';
    EXECUTE 'DROP TABLE IF EXISTS Organism';
END $$;
