START TRANSACTION;
    DROP PROCEDURE IF EXISTS Life.InsertOrganism;
    DROP FUNCTION IF EXISTS Life.GetAverageLifespan;
    DROP TRIGGER IF EXISTS Life.PrefixColourTrigger;
    DROP TABLE IF EXISTS Life.Animal;
    DROP TABLE IF EXISTS Life.Plant;
    DROP TABLE IF EXISTS Life.Organism;
    DROP SCHEMA IF EXISTS Life;
COMMIT;