name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up SQL Server
        run: |
          docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=password' -p 1433:1433 --name sql_server_container -d mcr.microsoft.com/mssql/server:2022-latest
          sleep 30

      - name: Install sqlcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -LJO https://aka.ms/sqlcmdexe
          unzip -q sqlcmd.zip -d /sqlcmd
          export PATH=$PATH:/sqlcmd
          sqlcmd -? > /dev/null

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Run tests
        run: python -m unittest test/test.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Branch
        run: |
          git push --delete origin ${{ github.ref }}
        if: success()