name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  tsql-test:
    runs-on: ubuntu-latest

    steps:
#      - name: Run ms-sql container
#        run: |
#          docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=StrongPword*8' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      
#      - name: Install ODBC Driver for SQL Server
#        run: sudo apt-get install -y unixodbc-dev

#      - name: Wait
#        run: sleep 20

#      - name: Set Environment Variables (TSQL)
#        run: |
#          echo "SQL_SERVER=localhost" >> $GITHUB_ENV
#          echo "SQL_DATABASE=master" >> $GITHUB_ENV
#          echo "SQL_UID=sa" >> $GITHUB_ENV
#          echo "SQL_PWD=StrongPword*8" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc

#      - name: TSQL Tests
#        run: python -m unittest test/test_tsql.py

#      - name: Stop ms-sql container
#        run: |
#          CONTAINER_ID=$(docker ps -q --filter ancestor=mcr.microsoft.com/mssql/server:2022-latest)
#          if [ ! -z "$CONTAINER_ID" ]; then
#            docker stop $CONTAINER_ID
#          fi

  plssql-test:
    runs-on: centos-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_oracle

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Run oracle container
        run: docker run --name oracle-server -e ORACLE_PWD=StrongPword*8 oraclelinux:8

      - name: Install oracle client
        run: sudo yum install -y oracle-instantclient-basic-21.12.0.0.0-1.el8.x86_64.rpm

      - name: Wait for oracle container
        run: sleep 20

      - name: Set Environment Variables (Oracle)
        run: |
          echo "ORACLE_SERVER=localhost" >> $GITHUB_ENV
          echo "ORACLE_SERVICE_NAME=ORCL" >> $GITHUB_ENV
          echo "ORACLE_USER=SYS" >> $GITHUB_ENV
          echo "ORACLE_PASSWORD=StrongPword*8" >> $GITHUB_ENV  

      - name: PLSQL tests
        run: python -m unittest test/test_plsql.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Branch
        run: |
          git push --delete origin ${{ github.ref }}
        if: success()