name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x

      - name: Run tests
        run: python -m unittest test/test.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Branch
        run: |
          git push --delete origin ${{ github.ref }}
        if: success()