name: Python Tests

on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: password
        ports:
          - 1433:1433

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup py installation
        uses: actions/setup-python@v2
        with: 
          python-version: 3.x
      
      - name: Install ODBC Driver for SQL Server
        run: sudo apt-get install -y unixodbc-dev

      - name: Check SQL Server Service Availability
        run: |
          python -c "import socket; host='localhost'; port=1433; sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM); result = sock.connect_ex((host, port)); print(f'Service Availability: {result}'); sock.close()"

      - name: Print Connection String Details
        run: |
          echo "SQL_SERVER=${SQL_SERVER}"
          echo "SQL_DATABASE=${SQL_DATABASE}"
          echo "SQL_UID=${SQL_UID}"
          echo "SQL_PWD=${SQL_PWD}"

      - name: Debug ODBC Environment
        run: odbcinst -j

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc

      - name: Run tests
        run: python -m unittest test/test.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Auto PR
          title: Automated PR
          body: Created by a development branch
          branch: main
          
      - name: Merge Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Merge PR
          title: Merge Pull Request
          body: This PR was automatically merged.
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Branch
        run: |
          git push --delete origin ${{ github.ref }}
        if: success()