BEGIN 
    EXECUTE IMMEDIATE 'DROP PROCEDURE InsertOrganism';
    EXECUTE IMMEDIATE 'DROP FUNCTION GetAverageLifespan';
    EXECUTE IMMEDIATE 'DROP TRIGGER PrefixColourTrigger';
    EXECUTE IMMEDIATE 'DROP SEQUENCE org_pk';
    EXECUTE IMMEDIATE 'DROP TABLE Animal';
    EXECUTE IMMEDIATE 'DROP TABLE Plant';
    EXECUTE IMMEDIATE 'DROP TABLE Organism';
END;
/
